oppdatert alt
ntnu-design/ntnu-avgangsutstilling-2023 pull request #98
Opened 2023-05-25 20:20 UTC by Misthalin

Skal være klar til å publiseres/oppdateres.

Jeg kan be alle om å se over sin egen side i morgen, om du publiserer denne, også får vi ta og fikse alle ev. feil over helga ellernoe

2023-05-26 17:19 UTC, kristwob reviewed
Skal alle bildene være .jpg? Eller skulle de være webp?

2023-05-26 17:20 UTC, Misthalin commented
@kristwob de er webp i public folderen, gadd bare ikke å slette de i _content, men tror ikke det har noe å si

2023-05-26 17:21 UTC, Misthalin commented
de som har png er fortsatt png da, men tror ikke det er så farlig(?)

2023-05-26 17:21 UTC, kristwob commented
Nei tror ikke det har så masse å si

2023-05-26 17:21 UTC, kristwob approved these changes

2023-05-26 17:22 UTC, merged

2025-04-09 18:22 UTC, UZ334334 requested changes
****[]()****